version: "3.9"
services:
    api:
      image: rianengracia/gma-news-api:v1.0.0
      build:
        context: .
        target: run
        args:
          VERSION_PREFIX: 1.0.0.0
          VERSION_SUFFIX: docker
      ports:
          - "8085:8080"
          - "8084:8081"
      environment:
        DOTNET_ENVIRONMENT: docker
        ConnectionStrings__PostgreSqlServer: ${ConnectionStrings__PostgreSqlServer}
      networks:
        - gma_news_api_network
      depends_on:
        - seq
    seq:
      image: datalust/seq:latest
      ports:
        - "5341:50"
      environment:
        ACCEPT_EULA: Y
      networks:
        - gma_news_api_network
networks:
  gma_news_api_network:
    driver: bridge
